version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
      - "9229:9229"
    command:
      - node
      - "--inspect"
      - "bin/www" 
    volumes:
      - .:/usr/src/app