version: '3.7'
services:
  server:
    image: node
    ports:
      - "3001:3000"
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    tty: true
volumes:
  node_modules: